### PR TITLE
Envire smurf

### PR DESCRIPTION
**Pull request by Rauldg**
- Motors are loaded too.
- Use the joint name in the joint object constructor.
- Each component type is loaded in its respective function.
- Tests.
- Compatible with the new configmaps

### CODE REVIEW

**Comment by jmachowinski** [comment]
The naming of the transformations breaks existing code.
Please change name to be the last parameter and default it to source+"2"+target

**Comment by Rauldg** [comment]
The problem with the source +"2"+ target naming convention is that is 
artificial in the sense that is not given in the smurf/urdf model. Why 
not using directly the name of the joint for the transformations?

Javi has a strong opinion on this one, so I include him in the the mail...

On 01.06.2016 10:05, jmachowinski wrote:

> The naming of the transformations breaks existing code.
> Please change name to be the last parameter and default it to 
> source+"2"+target
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/rock-cpp/smurf/pull/3#issuecomment-222921554, or 
> mute the thread 
> https://github.com/notifications/unsubscribe/AHtpu8NkD_qEP70DHQbSSiFmtu6Jb-Zpks5qHT00gaJpZM4Ip4fL.

## 

  Raúl Domínguez (M.Sc.)
  Space Robotics

  Besuchsadresse der Nebengeschäftsstelle:
  DFKI GmbH
  Robotics Innovation Center
  Robert-Hooke-Straße 5
  28359 Bremen, Germany

  Postadresse der Hauptgeschäftsstelle Standort Bremen:
  DFKI GmbH
  Robotics Innovation Center
  Robert-Hooke-Straße 1
  28359 Bremen, Germany

  Tel.:     +49 421 178 45-6617
  Zentrale: +49 421 178 45-0
  Fax:      +49 421 178 45-4150 (Faxe bitte namentlich kennzeichnen)
  E-Mail:   raul.dominguez@dfki.de

  Weitere Informationen: http://www.dfki.de/robotik

---

  Deutsches Forschungszentrum fuer Kuenstliche Intelligenz GmbH
  Firmensitz: Trippstadter Straße 122, D-67663 Kaiserslautern
  Geschaeftsfuehrung: Prof. Dr. Dr. h.c. mult. Wolfgang Wahlster
  (Vorsitzender) Dr. Walter Olthoff
  Vorsitzender des Aufsichtsrats: Prof. Dr. h.c. Hans A. Aukes
  Amtsgericht Kaiserslautern, HRB 2313
  Sitz der Gesellschaft: Kaiserslautern (HRB 2313)
  USt-Id.Nr.:    DE 148646973
  Steuernummer:  19/673/0060/3

**Comment by jhidalgocarrio** [comment]
+1
source+"2"+target is an artificial frame name, in the sense that it does not exist in SMURF.
It is a bad practice to create frame names in the C++ code. This is the reason why there are joint names in the SMURF/URDF.

**Comment by jmachowinski** [comment]
You can still set the name in my proposal, if not specified, it will just default to source2target

**Comment by Rauldg** [comment]
I introduced back the previous constructors. 
The optional parameter solution was complicated because I had to access to the getName method of the frame received as parameter in the header for the default value and the compiler was not happy with it.

Neverthless, if you use the method loadFromSmurf the transformations will still be named after the correspondent urdf joint name...

**Pull request merged**
