### PR TITLE
Use SMURF::Visual instead of urdf::Visual

### PR DESCRIPTION
**Pull request by Rauldg**
introduce smurf visual and smurf material to utilise additional color information from smurf files

@annaborn Why not having support for both types of visuals?

### CODE REVIEW

**Comment by annaborn** [comment]
We should check if the master branch is used in enter. If it is, we should keep smurf_visual. Since the changes in smurf_visual were not tested under enter project.
Other option, we can freeze the enter to specific commit from master branch and than merge. But until now, please keep smurf_visual branch.

**Comment by annaborn** [comment]
> @annaborn Why not having support for both types of visuals?
Smurf visual is nothing else than urdf visual, just with optional extra: material. 
To use one format is less error prone, since one common smurf description is used for any robot.

**Comment by Rauldg** [comment]
@annaborn 
For what I have seen, in Entern buildconf no override to smurf_visual exists.

The second option that you proposed is nicers, because we reduce the number of branches. Then we should:

0. Add override to fix the packages to [this commit](https://github.com/rock-cpp/smurf/commit/72ed09526bb8a25975696164fd1977f8323c56c9) and [this commit](https://github.com/envire/envire-envire_smurf/commit/2153c5354c8f6befbe7be588880366729a2a4084) in the entern buildconf
0. Test both MRs with our [working buildconf](https://github.com/Rauldg/simulation-buildconf/tree/rebasing_mars_and_envire_smurf) and fix if needed
0. Merge into master both repos
0. Remove the overrides on our [working buildconf](https://github.com/Rauldg/simulation-buildconf/blob/rebasing_mars_and_envire_smurf/overrides.d/01-envire-mars.yml#L14)

**Comment by Rauldg** [comment]
>Add override to fix the packages to this commit and this commit in the entern buildconf

Done

**Comment by annaborn** [comment]
@Rauldg Great! Thank you!
To the 1. point: we are using tools/smurf on smurf_visual branch and envire/envire_smurf on smurf_visual branch in rebasing_mars_and_envire_smurf. So both changes were tested.

So I would merge both.

**Pull request merged**
